name: Atualizar dados PowerBI

on:
  schedule:
    - cron: '*/30 * * * *' # roda a cada 30 minutos
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BI.py
        env:
          SENHA_REQUISICAO: ${{ secrets.SENHA_REQUISICAO }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_REVIEWS: ${{ secrets.URL_REVIEWS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_CREDENTIAL: ${{ secrets.DB_CREDENTIAL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python BI.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/dados_atualizados_feira.csv 
          if git diff --staged --quiet; then
            echo "Nenhuma alteração detectada. Pulando o commit/push."
          else
            echo "Alterações detectadas. Committing e pushing..."
            git commit -m "Atualiza dados automaticamente"
            git push
          fi